parameters:
  vmImage: 'macOS-10.14'
  pytestOpt: '--doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html'
  androidSdkVer: 28
  CI: true

jobs:
  - template: ./functional/run_android_test.yml
    parameters:
      name: 'func_test_android'
      vmImage: ${{ parameters.vmImage }}
      pytestOpt: ${{ parameters.pytestOpt }}
      testFiles: 'GnucashAndroidTest.py'
      sdkVer: ${{ parameters.androidSdkVer }}
      CI: ${{ parameters.ci }}
